# Generated by Django 5.2.7 on 2025-10-18 06:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Full name of the contacted person', max_length=200)),
                ('email', models.EmailField(blank=True, help_text='Email address (optional)', max_length=254, null=True)),
                ('phone', models.CharField(blank=True, help_text='Phone number (optional)', max_length=20, null=True)),
                ('facebook_url', models.URLField(blank=True, help_text='Facebook profile URL (optional)', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this contact', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ['-created_at'],
            },
        ),
    ]
