# Generated by Django 5.2.7 on 2025-10-18 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone number (optional)', max_length=30, null=True),
        ),
    ]
