# Generated by Django 5.2.7 on 2025-10-17 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='department',
        ),
        migrations.RemoveField(
            model_name='studentapplication',
            name='department',
        ),
    ]
