# Generated by Django 5.2.7 on 2025-10-17 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_address_alter_student_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='note',
            field=models.TextField(blank=True, help_text='Special notes about the student'),
        ),
    ]
