# Generated by Django 5.2.7 on 2025-10-17 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_teacher_department_and_more'),
        ('batches', '0003_remove_batch_department_alter_batch_academic_year_and_more'),
        ('core', '0001_initial'),
        ('students', '0002_remove_student_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='department',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
