# Generated by Django 5.2.7 on 2025-10-20 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0005_remove_batch_current_enrollment_and_more'),
        ('fees', '0001_initial'),
        ('students', '0004_student_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='studentpayment',
            name='unique_student_batch_payment',
        ),
        # Drop the foreign key columns first
        migrations.RemoveField(
            model_name='paymentimport',
            name='imported_by',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='processed_by',
        ),
        migrations.RemoveField(
            model_name='studentpayment',
            name='created_by',
        ),
        # Add them back with correct references
        migrations.AddField(
            model_name='paymentimport',
            name='imported_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentpayment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='studentpayment',
            unique_together={('student', 'batch')},
        ),
    ]
