"""
Django settings for student_management project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-%7)!f&f&(q%-22a0x+_clq7n1j0$*d75=nev53$xkyghx(12vh')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').lower() == 'true'

# Allow Railway and other production hosts
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1,*.railway.app,*.up.railway.app').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'django_extensions',
    
    # Custom apps
    'core',
    'accounts',
    'students',
    'batches',
    'fees',
    'contacts',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'student_management.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'student_management.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Use PostgreSQL for production, SQLite for development
if os.getenv('DATABASE_URL'):
    DATABASES = {
        'default': dj_database_url.parse(
            os.getenv('DATABASE_URL'),
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
    # Ensure we're using the correct PostgreSQL backend for psycopg3
    DATABASES['default']['ENGINE'] = 'django.db.backends.postgresql'
    # Additional PostgreSQL settings for better reliability
    DATABASES['default']['OPTIONS'] = {
        'connect_timeout': 10,
        'options': '-c default_transaction_isolation=read_committed'
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Firebase Configuration
FIREBASE_CONFIG = {
    'project_id': 'sma-student',
    'private_key_id': 'ddc98398f07f2365f1e6ca8b045f8eab327bbe4e',
    'private_key': '-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCwobiUV8yPzQCN\nl5xrjSKX9QdAVHShybSk4vaIFa+xGamSfm+HRX0qtAutFxJmlSQ/c12MlByEsnxt\nCRb1dkVgMyjizX2ZbtUY7NDupXsHwLqlsFhYGV8dBpnsFNFz6V8VVXu4HXa6HWZ/\n2JtRc2VlSeNPRdT+MXKzm8gIiC+JRqC3xYAijc3CB7dDVKa5WYqW6bbdI2QrbYZH\nXD2XSLehxJPXDEdN0YWHAqXUMmd4cfK65Mygw640ZXe7LMqvnMlm2dzUyEdlT59b\nz6SHl+jsWjiBqXeRCZJl2S6o6NIWi5EPYeopAFipVnmFb+v1OQ0IcXCIF+cNCVP1\nperlxr0DAgMBAAECggEABH6A50lam5gQOQoQAU6MgEhMQG9Frm4m6gEaW7kNiNiJ\nz3/nD46Nkj4Vg/hvz+tgijrBuRd1qEywTMfr7R/uwPVcR3UKCpLe2i0AXeoY+MgH\nF7smbEts95yY4wBeme/oqu7LYJJjWHXyCzO0M/zXKh4YqgYxVqxkajx++PSaHQiD\nrS4OO1lotIhUJXbHtW1LHWwx9TX8R2qyT9uyaeK0eiQZuV6WtbPB9TBGE2LqaWa+\n3Wm+AmorKucgmGubwrCtVrSLFHSYALU+3gZD532nW51NtS6NuFqrmD+wnq1vHGu0\nHMMcyZVlkmEnd3SQOUXKml2QdW9kVnddUKCt7MeUsQKBgQDgWGYDTPNyLKkR6ebt\nKy8offaUA2bzAFgzml3xSwttNB3IgsfgM2MsFhM8RPdDRaRNdfzMK5zWrCXrHmSw\n7tuuWDgso0qPZn3Bae6NvwZCRESzZWczWpfzzjQNEjvUGW2wIpKWI40jpZZTg1pF\nxRsb0gdR9LOFBJD9CQWVppe/UQKBgQDJjdrba1ffsv6W8zGEZ43cHYICAs/w6iWP\nsV4OCA6QYb3X7DUJyxCFqgKjkRMaUwTfgcMDu/mxhjUIf5S4JKF5uOgwO13ee7/k\nqI0zEbbABgP4Bld3u99R19nPUgrncXBkbEbC/Q4C7HUFwF88b4UNXCfTCtsrBEs8\nv/OwI4xqEwKBgQC3tIssTrnWl22GhrMbKE6AaM0eHL8TYwfWkaQ1bs8XiCKPS1Ai\nbdHaiuULaCnVQ1SsPV5ZTakrPGH8arHnFGB9Hi45lyj5zeJSG81E8tRMNRzQjct5\nCMj+0q5aucCWCJCCN30zRj9Pnks/bYLhOOre2Bg4axkJZljXaqjRB06hUQKBgBoE\nodfpR3KtHIhH5IB/DaT4eivgSQ+EakzeTJHrIFYrB+KzrzUQbZWTmLucoqanSN3B\nVndI8Lal6HqsXXpX4DBiWja/syJhPyg5SeDpzHmFTUXbK7ddHTrnbkqBAL9XuXZ9\nM7VADWr7MzAG4URf8QEEgG+R2zD2YO/6p255aErZAoGBANJw55OCHzzf018DyFWd\nES3H0gC/ziN0jeJ1f/I6UmIswlWStIbvHmmnr8GZ6UyISzU/6LZq8RHvrtjtGEDa\nATUiNDv1qYt0+sE8c/eFWg8cklxXFQv7PCrrUXdNj09UJlI6Mlyneya9KFe+235a\nDa2cYfrCF0Xf5aKSX0Y5zA0u\n-----END PRIVATE KEY-----\n',
    'client_email': 'firebase-adminsdk-fbsvc@sma-student.iam.gserviceaccount.com',
    'client_id': '116218628638223423506',
    'auth_uri': 'https://accounts.google.com/o/oauth2/auth',
    'token_uri': 'https://oauth2.googleapis.com/token',
    'auth_provider_x509_cert_url': 'https://www.googleapis.com/oauth2/v1/certs',
    'client_x509_cert_url': 'https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40sma-student.iam.gserviceaccount.com',
}

# Firebase Web Config
FIREBASE_WEB_CONFIG = {
    'apiKey': 'AIzaSyAC6jhWOKd06VhjV7RTyntVZwkDPGDcf-4',
    'authDomain': 'sma-student.firebaseapp.com',
    'projectId': 'sma-student',
    'storageBucket': 'sma-student.firebasestorage.app',
    'messagingSenderId': '621019846757',
    'appId': '1:621019846757:web:02faa1536bbb73969e0e8c'
}

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20
}

# CORS Configuration
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "http://192.168.68.103:8000",
    "http://192.168.68.103:3000",
    "http://192.168.68.53:8000",
    "http://192.168.68.53:3000",
    "http://192.168.10.153:8000",
    "http://192.168.10.153:3000",
]

# Allow all local network access for testing
CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOW_CREDENTIALS = True

# Currency API Configuration
CURRENCY_API_KEY = os.getenv('CURRENCY_API_KEY')

# Login URLs
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/'
