# Generated by Django 5.2.7 on 2025-10-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0003_remove_batch_department_alter_batch_academic_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
