# Generated by Django 5.2.7 on 2025-10-17 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0004_alter_batch_end_date_alter_batch_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='current_enrollment',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='max_capacity',
        ),
    ]
