# Generated by Django 5.2.7 on 2025-10-21 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0005_remove_batch_current_enrollment_and_more'),
    ]

    operations = [
        # Remove the existing unique constraint
        migrations.RunSQL(
            "ALTER TABLE batches_batch DROP CONSTRAINT IF EXISTS batches_batch_code_key;",
            reverse_sql="ALTER TABLE batches_batch ADD CONSTRAINT batches_batch_code_key UNIQUE (code);"
        ),
        # Add a partial unique constraint that only applies to active batches
        migrations.RunSQL(
            "CREATE UNIQUE INDEX IF NOT EXISTS batches_batch_code_active_unique ON batches_batch (code) WHERE is_active = true;",
            reverse_sql="DROP INDEX IF EXISTS batches_batch_code_active_unique;"
        ),
    ]
